---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: rabbitmq-pvc
  namespace: sock-shop
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: "standard-rwo"  # o "pd.csi.storage.gke.io"
  resources:
    requests:
      storage: 5Gi